### ISSUE TITLE
Klausursammlung

### ISSUE THREAD

**Issue by dokriseum** [fsr4/fsr4.github.io#11]
Klausursammlung ist nicht mehr aktuell und sollte daher entfernt werden.

**Comment by lotteunckell** [comment]
Klausursammlung ist nicht mehr aktuell und sollte daher **aktualisiert** werden.

**Comment by Kaes3kuch3n** [comment]
Ich hab den Text dazu schon aktualisiert und (außer in der Überschrift) Gedächtnisprotokolle hingeschrieben. Meint ihr die Überschrift von der Section, oder was genau soll geändert werden?

**Comment by dokriseum** [comment]
Ah super. Dann passt es. Bei mir war noch das alte, dass wir Altklausuren sammeln.

Die Überschrift "Klausurensammlung" kann man so lassen. Ungefähr stimmt das ja auch. Eventuell wäre eine andere Bezeichnung verwirrend.

**Comment by Kaes3kuch3n** [comment]
Done 👍
